import subprocess
HEAD = subprocess.check_output(['git', 'show', 'HEAD:memory/2026-06-29.md'])
WT = open('memory/2026-06-29.md', 'rb').read()
print(f'HEAD bytes: {len(HEAD)}')
print(f'HEAD first 10 bytes hex: {HEAD[:10].hex()}')
print(f'HEAD has BOM: {HEAD[:3] == bytes([0xEF, 0xBB, 0xBF])}')
print(f'HEAD CRLF count: {HEAD.count(bytes([0x0D, 0x0A]))}')
print(f'HEAD total LF count: {HEAD.count(bytes([0x0A]))}')
print()
print(f'WT bytes: {len(WT)}')
print(f'WT first 10 bytes hex: {WT[:10].hex()}')
print(f'WT has BOM: {WT[:3] == bytes([0xEF, 0xBB, 0xBF])}')
print(f'WT CRLF count: {WT.count(bytes([0x0D, 0x0A]))}')
print(f'WT total LF count: {WT.count(bytes([0x0A]))}')
print()
print('--- HEAD last 200 bytes ---')
print(HEAD[-200:].decode('utf-8', errors='replace'))
print('--- WT last 200 bytes ---')
print(WT[-200:].decode('utf-8', errors='replace'))